# Generated by Django 6.0.3 on 2026-03-08 05:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=50)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('BLIND', 'Blind')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=100)),
                ('hardness', models.CharField(choices=[('HARD', 'Hard'), ('MEDIUM', 'Medium'), ('EASY', 'Easy')], max_length=10)),
                ('link', models.URLField()),
                ('solved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('solved', models.CharField(choices=[('OWN', 'Own'), ('PARTIAL', 'Partial'), ('HINT', 'Hint'), ('FAILED', 'Failed')], max_length=10)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa.pattern')),
            ],
        ),
    ]
