# Generated by Django 6.0.3 on 2026-03-08 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solved',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solved_at',
        ),
        migrations.AlterField(
            model_name='problem',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='dsa.pattern'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('solved', models.CharField(choices=[('OWN', 'Own'), ('PARTIAL', 'Partial'), ('HINT', 'Hint'), ('FAILED', 'Failed')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='dsa.problem')),
            ],
        ),
    ]
