# Generated by Django 6.0.3 on 2026-03-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0002_remove_problem_solved_remove_problem_solved_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='solved',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='hardness',
            new_name='difficulty',
        ),
    ]
