# Generated by Django 6.0.3 on 2026-03-09 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0003_rename_solved_attempt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='solved_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
