# Generated by Django 6.0.3 on 2026-03-09 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa', '0004_alter_attempt_solved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='solved_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
